name: Build Docker Image & Push to AWS-ECS

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Latest Code
        uses: actions/checkout@v3

      - name: Login into AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Access Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECS_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
      - name: Scan Docker image for vulnerabilities
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECS_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull aquasec/trivy
          docker run --rm -v $(pwd):/workdir aquasec/trivy --exit-code 1 --severity HIGH $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Notify Build Status
        if: always()
        uses: cinotify/github-action@main
        with:
          to: "bhargavichiluka1898@gmail.com"
          subject: "build Status"
          body: "Build Github action executed. please check the status."
          
