name: Build Docker Image & Push to AWS-ECS

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Latest Code
        uses: actions/checkout@v3
